server:
  port: 8085
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.30.179:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.30.179:3306/gulimall_sms?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: 8520
  redis:
    host: 192.168.30.179
    port: 6379
mybatis-plus:
  mapper-locations: classpath:mapper/sms/**/*.xml
  global-config:
    db-config:
      id-type: auto


